### ISSUE TITLE
Spotify start failed

### ISSUE THREAD

**Issue by MaxRousset** [solus-project/3rd-party#102]
Spotify crash just after login

`[1226/111553:ERROR:resource_bundle.cc(808)] Failed to load /usr/share/spotify/cef_extensions.pak
Some features may not be available.
[1226/111558:ERROR:PlatformKeyboardEvent.cpp(94)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
Erreur de segmentation (core dumped)`

All logs:
[http://pastebin.com/RRAADJnc]

Reported here too : 
[https://solus-project.com/forums/viewtopic.php?f=10&t=2691]

**Comment by JoshStrobl** [comment]
This has already been reported at https://dev.solus-project.com/T1945

**Comment by JoshStrobl** [comment]
Resolved as of https://github.com/solus-project/3rd-party/commit/c3c3fd6e83655b09f7ee6f17b7d5399fb578f09f
