### ISSUE TITLE
Skype of linux alpha

### ISSUE THREAD

**Issue by combro2k** [solus-project/3rd-party#108]
Hi, 

I'm new to this awesome Solus project Distro.
So far I'm loving it :+1: :smiley: 

I've seen that the skype thirdparty is using skypeforlinux_1.15.0.1_amd64.deb while the 1.16.0.1 is available, tested it to change the location + hash, and it seemed to work. 
(Did this to test it a bit)
Another thing I found was 'libxscrnsaver-32bit' is added somehow to the dependencies, which is incorrect. This will add a lot of 32 bit libs which is incorrect, without it (tested it) it still works right,
or did I miss something?

Have never contributed yet to this 3rd party repository, so if you want me to fix that or guide me to the right place/owner? :smile: 

Cheers :netherlands:

**Comment by JoshStrobl** [comment]
Resolved as of 6f373026ec9e531dbaf55cd9aa57a21378bbc59e via @sunnyflunk.
