### ISSUE TITLE
Update TeamSpeak 3 to latest 3.1.0.1

### ISSUE THREAD

**Issue by der-eismann** [solus-project/3rd-party#109]
Dear Solus-Team,

please update your repository to support the latest TeamSpeak version 3.1.0.1.
https://www.teamspeak.com/downloads.html#

**Comment by sunnyflunk** [comment]
Is now updated https://github.com/solus-project/3rd-party/commit/b04466a3c7b806c4db0767bf35c91eab4dddb8f9
