### ISSUE TITLE
Update Vivaldi to Beta Builds, including Snapshot option

### ISSUE THREAD

**Issue by JoshStrobl** [solus-project/3rd-party#11]
As of November 4th, Vivaldi is no longer a Technical Preview. It is now [considered Beta](https://vivaldi.net/en-US/teamblog/66-the-first-vivaldi-beta).

**Note:** Links below go directly to .deb files. Don't click unless, well you actually wanna download the deb file.

Please update to the latest *beta* build, which is [1.0.303.52-5](https://vivaldi.com/download/vivaldi-beta_1.0.303.52-5_amd64.deb).

---

I would also appreciate making available a vivaldi-snapshot package, which obviously undergoes faster iteration and more updates than their beta builds. Their latest Vivaldi Snapshot is (*as of this issue comment*) [1.0.330.3](https://vivaldi.com/download/download.php?f=vivaldi-snapshot_1.0.330.3-1_amd64.deb).

**Comment by JoshStrobl** [comment]
Vivaldi updated to Beta as of de3e6e0d6deaf5546875902f90522ba5becc50ec

@Justinzobel mind porting over and updating your SUR vivaldi-snapshot to 3rd-party?

**Comment by jholtiv** [comment]
@JoshStrobl @Justinzobel I made a new pull addressing this issue to have vivaldi-beta and vivaldi-snapshot https://github.com/solus-project/3rd-party/pull/16

**Comment by JoshStrobl** [comment]
Closing thanks to work done by  @jholtiv via 4a0ca6f70eb7de106b4936739d9b2f67cbc978cb
