### ISSUE TITLE
Update Moneydance to current version

### ISSUE THREAD

**Issue by 30Mil** [solus-project/3rd-party#110]
Hello,

Monydance has added new version: 2017 Build 1597.

This is the link for the most (perpetual) current build. 
http://infinitekind.com/stabledl/current/moneydance_linux_amd64.deb 

The current script appears to use a vendor link from a 2015 version folder.

Thank you!

**Comment by Justinzobel** [comment]
Done as of https://github.com/solus-project/3rd-party/commit/c3514ac2c2e0950fe36381f4d585a3665a2e7974 please test.

**Comment by 30Mil** [comment]
Outstanding! Worked perfectly.
