### ISSUE TITLE
Update Discord Canary to the latest version.

### ISSUE THREAD

**Issue by Seeder101** [solus-project/3rd-party#113]
Hi guys ;)
just opened the discord and got a new update 0.0.14 version
so do you want to drop canary and replace it with the stable branch of discord ? 
Thanks

**Comment by JoshStrobl** [comment]
We're waiting for news from a Discord developer on whether we can distribute it in our repository or continue in 3rd-Party, hence why it hasn't been updated.

**Comment by Seeder101** [comment]
basically, you will ignore the latest update of the test-branch of discord (canary) up until a respond from the discord guys ?

**Comment by ikeydoherty** [comment]
Is there actually a canary update though or is that branch dead?

**Comment by Lochnair** [comment]
@ikeydoherty Just checked. The version available from the Discord website is now 0.0.1, and isn't named canary anymore. So yeah, seems dead.

**Comment by Seeder101** [comment]
there's a canary update... 
![screenshot from 2017-01-26 21-59-06](https://cloud.githubusercontent.com/assets/7802688/22345818/b5c55186-e412-11e6-9446-9596571c72e2.png)

**Comment by Lochnair** [comment]
Huh, they might be keeping it for pre-releases then. I tried to update the discord-canary package to 0.0.14, but it crashes on startup complaining about the 'libc++.so.1' shared library missing (the one from LLVM), which isn't packaged for Solus atm.

I packaged the new stable Discord release (0.0.1), which seems to work fine. See the PR here #114.

**Comment by DataDrake** [comment]
Discord has been in the Solus repo for a little while now. Not sure we need to update this anymore.

**Comment by JoshStrobl** [comment]
Given Discord Canary was already removed from Software Center and replaced with the discord repo item, as well as documentation on the installation of Discord Canary having since been removed from our documentation, I'm gonna go ahead and close this task and remove discord-canary from 3rd-Party.
