### ISSUE TITLE
Teamviewer not launching

### ISSUE THREAD

**Issue by tayspen72** [solus-project/3rd-party#116]
Neither the Teamviewer 12 shortcut or the terminal command to launch Teamviewer will launch the program.
Have tried stopping and restarting the service, uninstall and reinstall.

**Comment by Dgameman1** [comment]
When I first installed it and launched it. I had to wait a few minutes for it to actually appear

**Comment by tayspen72** [comment]
I have had it installed and been running it for a few weeks now. Just recently I have noticed that when I launch the program that it doesn't end up actually launching. I can try again and wait longer and report back.

**Comment by Justinzobel** [comment]
`systemctl status teamviewerd`

Output of that?

**Comment by tayspen72** [comment]
● teamviewerd.service - TeamViewer remote control daemon
   Loaded: loaded (/etc/systemd/system/teamviewerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-01-27 15:46:24 MST; 53s ago
  Process: 690 ExecStart=/opt/teamviewer/tv_bin/teamviewerd -d (code=exited, status=0/SUCCESS)
 Main PID: 692 (teamviewerd)
   CGroup: /system.slice/teamviewerd.service
           └─692 /opt/teamviewer/tv_bin/teamviewerd -d

**Comment by Justinzobel** [comment]
@tayspen72 can you please try running the commands from third party again: 

- sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/network/util/teamviewer/pspec.xml
- sudo eopkg it teamviewer*.eopkg;sudo rm teamviewer*.eopkg
Then once that's finished:
- sudo systemctl start teamviewerd.service

I've just done a fresh install and had no issues.

**Comment by tayspen72** [comment]
I have actually had it working since this issue was posted. I should have closed it long ago.
