### ISSUE TITLE
Steam not launching 

### ISSUE THREAD

**Issue by likelazyeyes** [solus-project/3rd-party#137]
Freezes infinity.

**Comment by ikeydoherty** [comment]
.. ? Steam isn't in 3rd party

**Comment by likelazyeyes** [comment]
Hmm yes but it is 3rd party

**Comment by JoshStrobl** [comment]
3rd-Party means this repo, not "3rd-Party vendors". Steam isn't in this repo, it's distributable and thus in the binary, main repo.

Please file your issue at https://dev.solus-project.com
