### ISSUE TITLE
Update PHPStorm to 2017.1

### ISSUE THREAD

**Issue by marcossffilho** [solus-project/3rd-party#138]
Released version: http://www.jetbrains.com/phpstorm/whatsnew/

**Comment by JoffreyHernandez** [comment]
You could update all jetbrains product from 2016.3 to 2017.1.

**Comment by DataDrake** [comment]
Well aware. Haven't had a chance to sit down and do it until now.

**Comment by DataDrake** [comment]
Still working on the others, but PHPStorm has been updated.
