### ISSUE TITLE
Bitwig 2.0 update

### ISSUE THREAD

**Issue by ckam03** [solus-project/3rd-party#144]
Bitwig 2.0 is out!

**Comment by sunnyflunk** [comment]
So I tried a straight update but needs some work to resolve

```
java.lang.UnsatisfiedLinkError: /opt/bitwig-studio/lib/bitwig-studio/libx11-windowing-system.so: /usr/lib64/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
```

**Comment by ckam03** [comment]
No worries

**Comment by sunnyflunk** [comment]
@ckam03 I have updated bitwig to 2.0 now. It includes a libxcb override (similar to what is required to load steam) as it links to an old version. 

I don't know how well it works (seemed to load and open fine, but not heavily tested), but from the menu will load it and `bitwig-wrapper` from the terminal, but `bitwig-studio` will not load from the terminal.
