### ISSUE TITLE
Webhook auto-update jetbrains package

### ISSUE THREAD

**Issue by denji** [solus-project/3rd-party#154]
Release Feed URL:
```
https://data.services.jetbrains.com/products/releases?code={productKey}[&type=eap]
```

* JetBrains PyCharm Community Edition - `productKey=PCC` / `executable=pycharm.sh`
* JetBrains PyCharm Educational Edition - `productKey=PCE` / `executable=pycharm.sh`
* JetBrains PyCharm Professional Edition - `productKey=PCP` / `executable=pycharm.sh`
* JetBrains IntelliJ Idea Community Edition - `productKey=IIC` / `executable=idea.sh`
* JetBrains IntelliJ Idea Ultimate Edition - `productKey=IIU` / `executable=idea.sh`
* JetBrains RubyMine - `productKey=RM` / `executable=rubymine.sh`
* JetBrains WebStorm - `productKey=WS` / `executable=webstorm.sh`
* JetBrains PhpStorm - `productKey=PS` / `executable=phpstorm.sh`
* JetBrains CLion - `productKey=CL` / `executable=clion.sh`
* JetBrains DataGrip - `productKey=DG` / `executable=datagrip.sh`

webhook is a lightweight configurable tool https://github.com/adnanh/webhook

**Comment by DataDrake** [comment]
As much time as this might save me (and do realize that I use the API to check for updates), it eliminates the most important step: Testing. Executable names change. Directories move. And tarballs without a bundled JDK/JVM become available. If you really don't want to have to wait on me, just use Jetbrains Toolbox.

**Comment by denji** [comment]
> tarballs without a bundled JDK/JVM become available
jetbrains switched to 64 bit mode

"jre/" && "jre64/" - `shutil.rmtree(".../jre{,64}")`
