### ISSUE TITLE
Add Stremio

### ISSUE THREAD

**Issue by leesei** [solus-project/3rd-party#168]
http://www.strem.io/

References:
https://www.htpcbeginner.com/install-stremio-on-linux-windows-and-mac/
https://aur.archlinux.org/packages/stremio-bin

**Comment by ikeydoherty** [comment]
Nope. No new packages going into Third Party, only flatpaks or similar will be supported now, sorry.

**Comment by leesei** [comment]
Copy that.

**Comment by ikeydoherty** [comment]
Plus there is the fact that Strem io is surrounded by controversy relating to legality .. Something we couldn't stick in our repos and support.

**Comment by ivanlechat** [comment]
It's an understandable and coherent answer. Thank you for taking the time to reply to it. I love Solus and is by far the most straightforward, functional and polished Linux distro I've ever used.
