### ISSUE TITLE
Chrome Stable Update to 59.0.3071.104

### ISSUE THREAD

**Issue by ChristianK89** [solus-project/3rd-party#170]
Hello Solus Team,

as comitted in IRC Channel i make an Update Request of third Party Application Google Chrome Stable 59.0.3071.104. 

Thank You

Best Regards

Christian

**Comment by Justinzobel** [comment]
Fixed thanks https://github.com/solus-project/3rd-party/commit/deaf061759e904744a28fea5caf0211e97b97431
