### ISSUE TITLE
WPS Office Alpha 21

### ISSUE THREAD

**Issue by Vistaus** [solus-project/3rd-party#173]
After a long, long time, Alpha 21 is finally out: http://wps-community.org/downloads

Hope you guys can update the 3rd party package to Alpha 21 :)

**Comment by JoshStrobl** [comment]
Was address with #172

**Comment by Vistaus** [comment]
Impossible. I've just hit the Check for updates button a couple of times but solus-sc never updated me to Alpha 21. So something's gotta be wrong with #172

**Comment by ikeydoherty** [comment]
PR was fucked.

**Comment by ikeydoherty** [comment]
Should help https://github.com/solus-project/3rd-party/commit/1fa123b73a848d8c971dfd3039710c7614f8284b

**Comment by Vistaus** [comment]
Ah, I see. Thanks for the fixin', I'll hit the Check for updates button again asap :)
