### ISSUE TITLE
Android Studio 2.3.3

### ISSUE THREAD

**Issue by aszrul** [solus-project/3rd-party#178]
Hi Solus Devs, there is new version available for Android Studio.
Link: https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip

Also for there is a problem for Android virtual emulator version 2.3.2 not being able to run unless I symlink the tools to the libstdc++.so.6.0.23 inside the system rather than using the libstdc++.so.6.0.22 provided inside the $ANDROID_SDK_HOME/emulator/tools/lib64/libstdc++/

Maybe the updates can help solving the problem above? 

Thank you very much 👍

**Comment by Justinzobel** [comment]
Fixed in https://github.com/solus-project/3rd-party/commit/b58f00efee13552d5b6015797bc4b813cd48549c

Let us know if there's any issues.
