### ISSUE TITLE
Unturned Crashes Budgie

### ISSUE THREAD

**Issue by Dizeeee** [solus-project/3rd-party#186]
I have crashes when running [Unturned](http://store.steampowered.com/app/304930/Unturned/) that bring down Budgie too. The screen goes black and puts me back at a gdm login screen. (Sidenote: I installed GNOME a while ago so thats why I have it, still crashed the same way before it was installed) This does not seem to be an issue with Unity, as other games run perfectly fine.

**Comment by JoshStrobl** [comment]
This should be reported on our Phabricator, not Third Party.
