### ISSUE TITLE
AnyDesk unable to connect

### ISSUE THREAD

**Issue by TangentDYN** [solus-project/3rd-party#193]
I was able to use the instructions to install AnyDesk.  It installed perfectly fine, but when trying to connect to another computer it gets stuck on the connecting screen.  I cannot close out of the app.  I have tried different things to get the app to close and it eventually locks up my computer.  

I really hope this can be fixed because I have fallen in love with Solus, but not being able to remotely connect to my home computers is somewhat of a deal breaker.   

Thanks for all the hard work!

**Comment by Justinzobel** [comment]
I've just updated AnyDesk to 2.9.4 and tested it by connecting from my laptop on Solus to the AnyDesk instance on my Windows desktop and it worked fine, was able to close it too. Please update and test.

**Comment by TangentDYN** [comment]
Strange.  There must be some other reason it isn't connecting for me.  I updated to the latest version and still having the same issue.  I will keep plugging away.  

On Friday, August 4, 2017, 8:46:49 PM PDT, Justin <notifications@github.com> wrote:


I've just updated AnyDesk to 2.9.4 and tested it by connecting from my laptop on Solus to the AnyDesk instance on my Windows desktop and it worked fine, was able to close it too. Please update and test.

**Comment by Justinzobel** [comment]
Any firewalls on the client or remote system?

**Comment by JoshStrobl** [comment]
Closing due to lack of response.
