### ISSUE TITLE
Webstorm -  ERROR: Cannot start WebStorm\nRequired tools are missing - check beginning of "/usr/bin/webstorm" file for details.

### ISSUE THREAD

**Issue by jhtrinh** [solus-project/3rd-party#198]
The application does not start. I do have "which" installed.
/usr/bin/webstorm: line 24: which: command not found
/usr/bin/webstorm: line 25: which: command not found
/usr/bin/webstorm: line 27: which: command not found
/usr/bin/webstorm: line 28: which: command not found
/usr/bin/webstorm: line 29: which: command not found
/usr/bin/webstorm: line 30: which: command not found
/usr/bin/webstorm: line 31: which: command not found
/usr/bin/webstorm: line 32: which: command not found
/usr/bin/webstorm: line 33: which: command not found
/usr/bin/webstorm: line 34: which: command not found
/usr/bin/webstorm: line 11: which: command not found
/usr/bin/webstorm: line 13: which: command not found
/usr/bin/webstorm: line 15: which: command not found
/usr/bin/webstorm: line 17: which: command not found

**Comment by DataDrake** [comment]
Let me take a look.

**Comment by DataDrake** [comment]
I don't see anything wrong with the current Webstorm. Please check that:

1. Your system is up to date
2. You have installed the latest version of Webstorm
3. You have not knowingly or unknowingly ended up with a modified ```PATH``` variable by checking the contents of ```~/.bashrc``` and/or running ```echo $PATH```

**Comment by jhtrinh** [comment]
I've just updated my packages from inside the Software Center, and installed the version of Webstorm that's in there as well.
My Path looks fine and it is not modified at all in .bashrc:
`$PATH=/usr/local/bin:/usr/bin:/bin`
I could try installing it via source.

**Comment by DataDrake** [comment]
Could you? I'm a bit out of ideas otherwise.

```
sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/programming/webstorm/pspec.xml
sudo eopkg it webstorm*.eopkg;sudo rm webstorm*.eopkg
```

**Comment by jhtrinh** [comment]
Still the same issue, for some reason which is not a command, i.e. it's not listed in /usr/bin

**Comment by DataDrake** [comment]
It's not complaining about ```which```, it's complaining about the commands the script is trying to find with it. Which is where my confusion comes in. Most of those commands are in ```coreutils``` and ```findutils``` which are part of a base install. So unless you removed something by accident or it is somehow getting a different PATH when running the script, I have no idea what the problem is.

Could you try running ```webstorm``` from a terminal and giving me the output?

**Comment by jhtrinh** [comment]
Ah the output above is what runs from the command line, if I try running the application from the start menu nothing happens.

**Comment by DataDrake** [comment]
Can you run ```eopkg check which```? ```which``` puts out a different output so I'm mistaken.

**Comment by jhtrinh** [comment]
It's broken, missing file /usr/bin/which

**Comment by DataDrake** [comment]
```
sudo eopkg it --reinstall which
```
Should get you sorted.

**Comment by jhtrinh** [comment]
Yep, that did it. Thank you!
