### ISSUE TITLE
Spideroak repository has moved

### ISSUE THREAD

**Issue by hexive** [solus-project/3rd-party#199]
FYI: Spideroak depreciated the repository https://spideroak.com/getbuild? used for this build. New repo is now located at https://spideroak.com/browse/share/golden/retriever/

latest version is 6.3.0

**Comment by Justinzobel** [comment]
I looked at that URL but it only has 6.3.0, yet the front page https://spideroak.com/release/spideroak/deb_x64 has 6.3.1?

**Comment by Vistaus** [comment]
It now has 7.0.0 in the repository.
