### ISSUE TITLE
Google Earth Update Required

### ISSUE THREAD

**Issue by EP01** [solus-project/3rd-party#202]
Version 7.3.0.3832 is now available [here](https://dl.google.com/linux/earth/deb/pool/main/g/google-earth-pro-stable/google-earth-pro-stable_7.3.0.3832-r0_amd64.deb). Changelog currently unavailable.

**Comment by EP01** [comment]
@Justinzobel fixed this on 24/08/2017 but forgot to close the issue.

**Comment by Justinzobel** [comment]
Ah damnit, thanks @EP01
