### ISSUE TITLE
Suggestion: Sublime Text

### ISSUE THREAD

**Issue by timojuonoja** [solus-project/3rd-party#21]
Since user repository was removed and that contained packaging Sublime Text to Solus..
I would suggest 3rd-party to support Sublime Text packaging? Is it possible?

**Comment by JoshStrobl** [comment]
@timojuonoja
FI (*Guessing by the name, you're Finnish?* :stuck_out_tongue:): Kyllä, voin ehkä tänään tai huomenna. Haluatkö Sublime Text 2 tai 3?
En: Sure, I can maybe today or tomorrow. You want Sublime Text 2 or 3?

**Comment by timojuonoja** [comment]
@JoshStrobl Yes, I'm a Finn :smile:. I would prefer Sublime Text 3. But surely you can package both, if there are people needing v2 also?

**Comment by JoshStrobl** [comment]
Assuming they don't conflict, yea I can add both. If they conflict for whatever reason I'll add **3**.

**Comment by JoshStrobl** [comment]
Sublime Text 3 added as of 53fefc18be3e501f490ea5709c2c267253bccb2 :smile: 
Due to the unsupported nature of Sublime Text 2, in addition to the likelihood of it conflicting (particularly their "sublime-package" files), I won't be landing that
