### ISSUE TITLE
Can not install adobe flash PPAPI

### ISSUE THREAD

**Issue by vince0708** [solus-project/3rd-party#212]
I can not install the adobe flash PPAPI via the softarecentre and terminal. It gave a error: Kan bestemmingbestand niet bereiken "https://www.solus-project.com/source/flash_player_ppapi_linux.x86_64.tar.gz": [Errno 14] HTTPS Error 404 - Not Found

(Englisch: can not reach destination)
![schermafdruk van 2017-09-13 13-43-11](https://user-images.githubusercontent.com/31923690/30375625-87ac72da-9889-11e7-86e9-afd0bab1cf69.png)

**Comment by Justinzobel** [comment]
Likely a new version out. I'll look into this when I get home.

**Comment by Justinzobel** [comment]
Fixed for both npapi and ppapi. Please try install again and thanks for the report.
