### ISSUE TITLE
adobe flash (ppapi) not working opera/vivaldi

### ISSUE THREAD

**Issue by vince0708** [solus-project/3rd-party#216]
After installing adobe flash (ppapi) via software center (and also via terminal) it is not working. Both browser Opera end Vivaldi can not play flashcontent.
![schermafdruk van 2017-09-14 16 22 26](https://user-images.githubusercontent.com/31923690/30435456-1607e290-996a-11e7-8c99-cc66c6ebd6d3.png). I also tried installing it manually. Flash is working for Chrome (out of the box)
and Firefox  (after allowing DRM)

**Comment by JoshStrobl** [comment]
Known issue, see: https://dev.solus-project.com/T3867

**Comment by Justinzobel** [comment]
I managed to play flash with vivaldi-stable when testing the new flash version.
