### ISSUE TITLE
How to add Apps for try in Solus ?

### ISSUE THREAD

**Issue by liberodark** [solus-project/3rd-party#225]
Hello,

How to add my apps for try in solus ?

Cordialy

**Comment by liberodark** [comment]
And for what have python and not pkgbuild ? similary from arch linux ?

Cordialy

**Comment by ikeydoherty** [comment]
Third Party is a legacy system that uses an ancient build system. Modern Solus packages use `ypkg` (`package.yml`) which has many strengths over pkgbuild. Solus itself has nothing to do with Arch Linux.

This repository will not see any new packages added, instead they will gradually all be removed and replaced with either native or snap options. Open source packages should be made available via snaps, or via the Solus repositories

**Comment by ikeydoherty** [comment]
If you want your apps in Solus directly, we can work with you on https://dev.solus-project.com to get them included directly (and you won't need to deal with the ugly crap that is this third party mechanism)

We can keep this issue active to discuss it - just marking it closed in the third-party sense.

**Comment by liberodark** [comment]
have try is not easy is yml have view.

**Comment by liberodark** [comment]
But have apps for work and is not on Solus.
I Love solus idea for rolling release is good but is not easy have help for me ?
Actualy im work to port https://github.com/liberodark/3rd-party/tree/master/desktop/r-studio-for-linux
For work wich this apps im packager from aur but yml is not same im lost :(

**Comment by DataDrake** [comment]
We have plenty of documentation on how to use `ypkg` and the `package.yml` format.

Requesting a Package (even if you are planning on submitting yourself)
https://solus-project.com/articles/packaging/request-a-package/en/

Building Solus Packages (We don't use the old pisi builder for new packages, we use `ypkg`)
https://solus-project.com/articles/packaging/guide/en/

How to Submit Patches
https://solus-project.com/articles/packaging/submitting-a-package/en/

**Comment by liberodark** [comment]
But have send this package but is not in solus : https://dev.solus-project.com/T3979

**Comment by Justinzobel** [comment]
You've requested it, it needs to be approved, then packaged and entered into the unstable repository, tested and then released to the default stable channel, these things don't happen overnight.

**Comment by liberodark** [comment]
but my account have been disable for have submit cudatext for what ?

**Comment by JoshStrobl** [comment]
@liberodark Removed comment. You actively were derailing conversations on Phabricator, triaging issues after I had requested you not, and rather than providing information on package requests, you ranted about Solus needing an AUR and package selection. Let's not derail other issues on other repos either, thank you.
