### ISSUE TITLE
Android Tools 26.0.0.1

### ISSUE THREAD

**Issue by moriel5** [solus-project/3rd-party#233]
I had been erroneous about ADB&Fastboot being severely outdated, due to me confusing the link it was downloading it from, as being from the API23 (Android 6.0) branch, and I am sorry about that.

Nevertheless, it would be good if the package will be updated, from version 26.0.0 to 26.0.0.1.

**Comment by JoshStrobl** [comment]
26.0.1 release notes:

> Fixed fastboot problems on macOS 10.13 High Sierra

Yea, I see no reason why this needs to be updated. There isn't anything generic or Linux related items that it solves.

**Comment by moriel5** [comment]
In that case, I concede.

I guess I'll have to try harder at searching for ADB&Fastboot"s release notes.
