### ISSUE TITLE
Google Chrome Beta download link updated

### ISSUE THREAD

**Issue by mfossen** [solus-project/3rd-party#24]
Building the eopkg failed when it couldn't download the Chrome Beta .deb.

Looks like the beta has been updated to:

http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-beta/google-chrome-beta_51.0.2704.63-1_amd64.deb

(which matches the current download at https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb)

Once I updated the pspec file it built and installed fine.

**Comment by Justinzobel** [comment]
This the one you're talking about? https://github.com/solus-project/3rd-party/commit/4cd84c3f902cdb2bb9dff7a248486845698cc595

**Comment by mfossen** [comment]
That's the one!
