### ISSUE TITLE
Can you add Gogland?

### ISSUE THREAD

**Issue by phonicmouse** [solus-project/3rd-party#245]
https://www.jetbrains.com/go/

**Comment by JoshStrobl** [comment]
As stated on our README:

> Note: This repo will not accept NEW packages as we are replacing the majority of them in Solus with Snaps.

Furthermore, these sorts of requests should be done in the form of [Package Requests](https://solus-project.com/articles/packaging/request-a-package/en) on Phabricator against the Third Party Repository tag.

**Comment by phonicmouse** [comment]
I'll do it. Thanks.

**Comment by ahahn94** [comment]
@phonicmouse You can use the goland snap.
With the new 2017.3 release, they renamed gogland to goland and started offering a snap version.
Just `sudo snap install goland --classic`.
I think they want to offer all of their IDEs as snaps in the near future.
