### ISSUE TITLE
Missing packges ...please bring those in

### ISSUE THREAD

**Issue by unixbhaskar** [solus-project/3rd-party#247]
These pkgs are missing 

`
bhaskar@soluslinux_05:17:28_Mon Nov 06:~> sudo eopkg search postfix

bhaskar@soluslinux_05:17:39_Mon Nov 06:~> sudo eopkg search sendmail

bhaskar@soluslinux_05:17:52_Mon Nov 06:~> sudo eopkg search exim

`

Returns nothing!

**Comment by Justinzobel** [comment]
This is not the place for package requests, please see https://solus-project.com/articles/packaging/request-a-package/en/ for more info.

**Comment by unixbhaskar** [comment]
Look like you are too quick on it. You directed page doesn't make any sense. Those pieces are there in wild for a long time and I am bemused by your ignorance ..hell ...give yourself a chance dear.
