### ISSUE TITLE
installing Franz in Solus

### ISSUE THREAD

**Issue by rpgood** [solus-project/3rd-party#254]
attempted to install Franz per instructions....received the following message:

DEBUG: return value for "wget https://raw.githubusercontent.com/meetfranz/franz-pkgbuild/master/franz.sh" is 8
Program terminated.
Command "wget https://raw.githubusercontent.com/meetfranz/franz-pkgbuild/master/franz.sh" failed, return value was 8.

what am I doing wrong???

**Comment by ahahn94** [comment]
The package is outdated. The url to the script leads to an error 404 (not found), thus the wget error.
