### ISSUE TITLE
Image Viewer - not displaying all colors - maybe other apps too

### ISSUE THREAD

**Issue by lourivellini** [solus-project/3rd-party#270]
Had the same issue in chrome.  Had to go into chrome://flags and force color profile to sRGB.  How when I look at this image of a color picker side by side - its shown correctly in chrome and way off in image viewer.

https://i.imgur.com/ipTxmmo.png
(left is chrome, right is image viewer)

Im wondering why this is happening in some apps.  For me this has been an issue only in Solus.

**Comment by ikeydoherty** [comment]
Thats not a third party app, please report to dev.solus-project.com
