### ISSUE TITLE
TeamViewer 13 update

### ISSUE THREAD

**Issue by Stupendoussteve** [solus-project/3rd-party#275]
TeamViewer has released packages for version 13.0.6634. It looks like it is a full release, but an unfinished product. Depends on some qt pieces now.

Here is the webpage: https://www.teamviewer.com/en/download/linux/

Unfortunately it is not possible for version 12 to connect to version 13 hosts, so the current Solus-provided package doesn't let you connect to a Mac or Windows system running the current release.

**Comment by ahahn94** [comment]
I had a look into it the other day but did not get it working. It crashes without an error message or log entry when trying to start the gui. I added some dependencies but maybe I was still missing one...
Maybe one of the repo admins will have a look into it, but it is still only a preview...

**Comment by Justinzobel** [comment]
Only a preview and the build I tried maybe a week ago wouldn't work at all even connecting between the same versions on two linux machines.

**Comment by Stupendoussteve** [comment]
It may be a Preview but it is the one that comes up on the Linux download page, they hide 12 under the previous releases. With 13 being the stable for the other platforms 12 becomes useless unless you are only connecting to other Linux machines.

There are qt dependencies now, I have the plain Linux .tar.gz running fine but had to install:
qt5-webkit
qt5-x11extras
qt5-base
qt5-declarative
qt5-sensors
qt5-multimedia
qt5-webchannel

Unsure about connecting two Linux boxes, I've had no problem connecting to Windows.

**Comment by Vistaus** [comment]
@Justinzobel "Only a preview"? Sure, but then someone needs to spank the developers for putting it on the Download page. 'Cause when you go to Download --> Linux, this is the only release that shows up.

**Comment by lukas15442** [comment]
How can install teamviewer at the moment?
from https://solus-project.com/articles/software/third-party/en/ I execute
`sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/network/util/teamviewer/pspec.xml`

output is:

`pspec.xml                      (4.0 KB)100%     42.41 MB/s [00:00:00] [vollständig]
actions.py                     (1.0 KB)100%     24.55 MB/s [00:00:00] [vollständig]
DEBUG: InstallDB initialized in 0.00573205947876.
DEBUG: RepoDB initialized in 0.000131130218506.
DEBUG: Zugriff auf Datei nicht möglich. Heruntergeladene Teile der Datei werden gelöscht.
Quellpaket wird erstelltt: teamviewer
component.xml                  (44.0  B)100%    780.19 KB/s [00:00:00] [vollständig]
Quelle wird abgerufen von: https://download.teamviewer.com/download/version_12x/teamviewer_12.0.85001_i386.deb
DEBUG: Zugriff auf Datei nicht möglich. Heruntergeladene Teile der Datei werden gelöscht.
Versuche Ersatzadresse: https://www.solus-project.com/source/teamviewer_12.0.85001_i386.deb
DEBUG: Zugriff auf Datei nicht möglich. Heruntergeladene Teile der Datei werden gelöscht.
*** 0 Fehlermeldung(en), 1 Warnung(en)
Programm beendet.
Zieldatei konnte nicht abgerufen werden "https://www.solus-project.com/source/teamviewer_12.0.85001_i386.deb": [Errno 14] HTTPS Error 404 - Not Found`

**Comment by Vistaus** [comment]
Well, like it says: the deb file is not available anymore. In fact, it seems like the deb file is fully removed from the Solus website. So I guess we'll have to wait for it to return or wait for the Teamviewer 13 update.

**Comment by Staudey** [comment]
@Vistaus @lukas15442 I created a pull request to fix the download link and update to the latest Teamviewer 12 release. Until it is merged you can use the following link to my edited pspec.xml instead of the one mentioned in the instructions you linked:

[https://raw.githubusercontent.com/Staudey/3rd-party/patch-3/network/util/teamviewer/pspec.xml](https://raw.githubusercontent.com/Staudey/3rd-party/patch-3/network/util/teamviewer/pspec.xml)

**Comment by sunnyflunk** [comment]
Note 3rd-party are **never** on the Solus site (it's 3rd-party as we can't distribute it). pisi came with a fallback url system, which is the only reason it has a solus-project url after it fails to download it from teamviewer. Is now merged, so should be working.

**Comment by Staudey** [comment]
Nevermind, it was just merged by sunnyflunk :smile: 

The instructions on the Third-Party help page should work again now

**Comment by ITHanke** [comment]
Great its working now!

**Comment by GueGuerreiro** [comment]
@jvdneste Thanks, I got Version 13 running on my system now, with seemingly no issues so far :)

**Comment by landrykid** [comment]
If you're having problems with v13 and want to use the [Solus 3rd Party](https://solus-project.com/articles/software/third-party/en/) commands, make sure to also install v12 software on the other machine.  Packages are available from the TeamViewer [previous versions page](https://www.teamviewer.com/en/download/previous-versions/).

**Comment by DataDrake** [comment]
Resolved.
