### ISSUE TITLE
Flashplayer cannot be installed.

### ISSUE THREAD

**Issue by chdslv** [solus-project/3rd-party#281]
`Program terminated.
Could not fetch destination file "https://www.solus-project.com/source/flash_player_ppapi_linux.x86_64.tar.gz": [Errno 14] HTTPS Error 404 - Not Found
`

**Comment by sunnyflunk** [comment]
Should be fixed with https://github.com/solus-project/3rd-party/commit/1884b31ae5268c6756a8d251450b9b9dbb2d5ce9
