### ISSUE TITLE
Synergy

### ISSUE THREAD

**Issue by ThomasAuriel** [solus-project/3rd-party#284]
Synergy is an app able to "share" the mouse and keyboard of a computer with other one. Basicly, you can use a single mouse on several computers.
The website: https://symless.com/synergy

I moved recently to Solus. The lack of synergy prevenst me to use the distro on all my computers. I did not find a nice opensource alternative. So I think this app should be added.

Thanks,
Thomas

**Comment by aszrul** [comment]
They are not accepting new 3rd party packages request here as far as I know.

> Note: This repo will not accept NEW packages as we are replacing the majority of them in Solus with Snaps. After the Ubuntu Rally (NYC) at the end of September 2017, we'll have Snaps integrated in the Software Center, and will begin forceful deprecation of this repository.
