### ISSUE TITLE
Slack available as a snap

### ISSUE THREAD

**Issue by mcritchlow** [solus-project/3rd-party#291]
I'm not sure what the best course of action here is, but now that Slack is available as a snap it seems like doing the packaging here is unnecessary and redundant as the snap works great. 

Should it be removed from this repo? Or should that wait until snaps are integrated more into the Software Center?

**Comment by JoshStrobl** [comment]
No, it shouldn't be removed from the repo, seeing as there's no way to install it in the Software Center yet and we're yet to actually pull the trigger on moving Third Party over to snaps.
