### ISSUE TITLE
Ocenaudio install failure

### ISSUE THREAD

**Issue by Squoose** [solus-project/3rd-party#304]
Hi, When I use the install commands for Ocenaudio on this page: 
https://solus-project.com/articles/software/third-party/en/

I get this:

Building source package: ocenaudio
component.xml                  (48.0  B)100%    204.80 KB/s [00:00:00] [complete]
Fetching source from: https://www.ocenaudio.com/downloads/index.php/ocenaudio_debian64.deb
ocenaudio_debian64.deb         (11.0 MB)100%    293.64 KB/s [00:00:00] [complete]
Source archive is stored: /var/cache/eopkg/archives/ocenaudio_debian64.deb
Unpacking archive(s)...
Program terminated.
unpack: check_file_hash failed
Please use 'eopkg help' for general help.

**Comment by sunnyflunk** [comment]
Try it again now

**Comment by Squoose** [comment]
It's working now, thanks!
