### ISSUE TITLE
IntelliJ IDEA Community Edition

### ISSUE THREAD

**Issue by tenten8401** [solus-project/3rd-party#310]
Is it possible we could get the Community Edition for IntelliJ IDEA?

**Comment by DataDrake** [comment]
> Note: This repo will not accept NEW packages as we are replacing the majority of them in Solus with Snaps. After the Ubuntu Rally (NYC) at the end of September 2017, we'll have Snaps integrated in the Software Center, and will begin forceful deprecation of this repository.

We are still working on integration into the Software Center, but we are no longer accepting new entries into 3rd-party. 

I have personally verified that you will have no problem achieving a similar result by following the official instructions for installing IDEA CE via Snap:

https://blog.jetbrains.com/idea/2017/11/install-intellij-idea-with-snaps/

**Comment by tenten8401** [comment]
Ahh, my bad.
I just ended up going with the IntelliJ Toolbox for the time being, which works really nice on Solus so far.

**Comment by ahahn94** [comment]
@tenten8401 you can also just use IntelliJ Idea Community via the snap package provided by JetBrains.
Just `snap install intellij-idea-community --classic`.
It is auto-updating, so all you have to do with this package is to let Idea update the plugins from time to time when you get the notification. The IDE will always be up to date. :wink: :grin:

**Comment by tenten8401** [comment]
I guess that works too and might be the better option if Solus plans on supporting Snaps, which I believe it is.
