### ISSUE TITLE
Microsoft Core Fonts fails to download

### ISSUE THREAD

**Issue by ggdaynight** [solus-project/3rd-party#350]
**Microsoft Core Fonts - third party repository** has non-working urls. Needs to change for another mirror, because the current one (razaoinfo) is not listed officially anymore. See here: [SourceForge Mirrors](https://sourceforge.net/p/forge/documentation/Mirrors/).

Better **solution** would be not a specify mirror, but for pool url, so it won't depend on the specific mirror.
E.g.:  https://downloads.sourceforge.net/corefonts/the%20fonts/final/andele32.exe

Thank you.

**Comment by Staudey** [comment]
This can be closed as fixed now, since the PR was merged.

**Comment by ggdaynight** [comment]
I don't know if it's my duty to do it, but I've opened it, I will close it.

Thanks everyone. And thank you @sunnyflunk .
