### ISSUE TITLE
Problems with Skype versions >= 8.20.76.1 (resp. 8.20.0.9)

### ISSUE THREAD

**Issue by Staudey** [solus-project/3rd-party#352]
As mentioned in PR #340 every version of Skype after 8.20.76.1 has issues with the tray icon on Budgie (and MATE), like in this screenshot: [https://i.imgur.com/cQ1Lg3b.png](https://i.imgur.com/cQ1Lg3b.png)

After reporting this via the Skype feedback function and some Skype feedback website I also created a post/question on the Microsoft community forums (answers.microsoft.com), where several other people also reported the same problem (not on Budgie but on xfce and GNOME; links below). After a couple of days with rather unhelpful responses a different Microsoft moderator said the following:

> Hello everyone,
>thank you for reporting this issue.
>Skype for Linux 8.20 got updated to GTK3, which might be the rootcause.
>As for the tray icon, would you please try installing "libappindicator3" and let me know if it helps in any way?

I see a "libappindicator" in the repo, version 12.10.0, which is already installed. Is that equivalent to what the moderator suggested? Could the upgrade to GTK3 really be the issue and can this be resolved on the side of Solus, or is the onus still on Skype?

Note: Since I hadn't tried it for some time and the moderator also suggested it, I once again tried the snap version of Skype as an alternative. But I still have severe issues with that one. As in no audio support at all. So I would say that the snap isn't really a replacement at the moment.

Note 2: I finally figured out that some of the versions I updated here where actually not the stable versions, only the ones of the form 8.x.0.x are. This caused some needless updating as they will show the update notification as soon as a new "unstable" (or whatever their term is) version is available, whereas the time between two stable releases is much longer. Apologies for that.

Links to the posts in the Microsoft forums:
[My post](https://answers.microsoft.com/en-us/skype/forum/skype_linux-skype_startms-skype_installms/issue-with-skype-tray-icon-starting-with-version/82dcc7bb-cd51-4d31-a843-e8cc949564e6?tm=1525093451408)
[Other post](https://answers.microsoft.com/en-us/skype/forum/skype_linux-skype_startms-skype_installms/system-tray-icon-in-xfce/d3f162bf-0bbf-481b-90a1-f43cae9a86cc?auth=1)

**Comment by Staudey** [comment]
Okay, the libappindicator3 thing didn't fix the problems for anyone in the thread. Seems like they are now working with the Electron team on this:

>Thank you for reporting it and providing the details. We are escalating the issue to the Electron team.

**Comment by Staudey** [comment]
Small update: Latest version of Skype still doesn't fix this BUT it seems the snap version is finally in a usable state. Now audio and video both work perfectly on my system.

**Comment by Staudey** [comment]
Another small update: with the "XDG_CURRENT_DESKTOP=ubuntu:GNOME" env variable the tray icon is big and blurry, but not duplicated. Might actually be an option to

**Comment by Staudey** [comment]
Didn't mean to close this. Also, a Skype moderator gave me a link to the relevant Electron bug report:

https://github.com/electron/electron/issues/12791

**Comment by JoshStrobl** [comment]
Not really sure why this is being reopened, it isn't something that we'd be directly responsible for resolving. Skype ships with its own Electron and thus the burden is on them to rebase on any upstream release that may resolve the issue.

**Comment by Staudey** [comment]
I was just using this to keep track of the issue, you can close it of
course if you want.

**Comment by truongnguyen-ntq** [comment]
One way to fix this is by reducing the taskbar width to 36px
`Budgie desktop setting > Botton panel > Settings`
