### ISSUE TITLE
Update AnyDesk to 4.0.0

### ISSUE THREAD

**Issue by drohm** [solus-project/3rd-party#425]
New features include:

* Address book
* Session comments
* Session recording and playback
* New permission interface
* TCP hole punching improvements - The TCP hole punching mechanism has been improved for kernel ≥ 3.9
* SystemD improvements
* Disabled access to the action menu, when the session has not been fully established
* The “remember password” checkbox is now disabled, if this is prohibited by the remote side
* Added an error message when connecting to an unsupported display server (e.g. Wayland)
* Fixed a session crash, when using “sudo su” in a terminal over AnyDesk

Tarbal can be downloaded here: https://download.anydesk.com/linux/anydesk-4.0.0-amd64.tar.gz

**Comment by sunnyflunk** [comment]
Per commit. You likely need to be more specific in terms of `resolves #425`
