### ISSUE TITLE
Update WPS Office to latest version

### ISSUE THREAD

**Issue by Vistaus** [solus-project/3rd-party#457]
Today, a new version of WPS Office was released: http://wps-community.org/downloads

**Comment by Staudey** [comment]
Oh, interesting. I've been looking at their page so often these past few months and no news, and just after I stopped doing that they come out with a release ^^

Will take a look in a few minutes

**Comment by Vistaus** [comment]
Thanks a lot! :)

**Comment by DataDrake** [comment]
Resolved.

**Comment by circlenaut** [comment]
There's been a new release for 2019:
http://wps-community.org/download.html

**Comment by Staudey** [comment]
@circlenaut Two things about this:

1. This is the old repository, the new one is found here: https://github.com/getsolus/3rd-party
2. WPS Office is no longer part of the 3rd party repository because of their weird license, see here: https://github.com/getsolus/3rd-party/issues/9
