### ISSUE TITLE
Add Tracktion Waveform

### ISSUE THREAD

**Issue by ryanpcmcquen** [solus-project/3rd-party#516]
I know this is deprecated ... but I have reached out to Tracktion to provide a Snap and they have no plans to at this time ... so I'm hoping my favorite distro might consider repackaging their `.deb` here ...

https://www.tracktion.com/products/waveform

**Comment by ahahn94** [comment]
I would suggest that you take a look here: https://github.com/ahahn94/my-3rd-party

**Comment by ahahn94** [comment]
Oh, and this repo is deprecated, we are now maintaining https://github.com/getsolus/3rd-party
