### ISSUE TITLE
Update Enpass

### ISSUE THREAD

**Issue by Weasy666** [solus-project/3rd-party#519]
Hi guys.
I appreciate your work and would like to request an update of Enpass. A few days before Sinew released Enpass 6 to the public. The installation guide for Linux is here https://www.enpass.io/support/how-to-install-enpass-on-linux/. I know that this repo is going to be deprecated but Enpass is not available as a snap package.

Thanks again for your work.

**Comment by ahahn94** [comment]
Hi.
We are not maintaining this repo anymore. You can find the new repo under https://github.com/getsolus/3rd-party. Enpass has already been updated there. The install instructions can be found here https://getsol.us/articles/software/third-party/en/

**Comment by Weasy666** [comment]
Oh...ok. Thx for the info.
