### ISSUE TITLE
Teamspeak 3 link broken

### ISSUE THREAD

**Issue by eivinfu** [solus-project/3rd-party#65]
The link for the raw github file 'pspec.xml' is broken on :
https://wiki.solus-project.com/3rdParty#Teamspeak_3

Current: 
https://raw.githubusercontent.com/solus-project/3rd-party/master/network/im/teamspeak3/pspec.xml

Should be: 
https://raw.githubusercontent.com/solus-project/3rd-party/master/network/im/teamspeak/pspec.xml

[ from \***/teamspeak3/**\* to \***/teamspeak/**\* ]

**Comment by JoshStrobl** [comment]
Fixed.
