### ISSUE TITLE
Scrivener installation

### ISSUE THREAD

**Issue by erikdubois** [solus-project/3rd-party#75]
I believe something went wrong when installing scrivener. (on two computers)
Take a look where the icons of scrivener ended up. 
![scrivener](https://cloud.githubusercontent.com/assets/10594806/19921122/c4097782-a0dc-11e6-9458-5ed78ee934c3.png)
16x16 22x22 etc... 256x256 all hold the folder apps and inside it Scrivener.png

I was so certain scrivener was third party ... upon checking this topic should be moved somewhere else. I let you take care of it.

**Comment by erikdubois** [comment]
i am going to report this here https://dev.solus-project.com/

**Comment by JoshStrobl** [comment]
Resolved as of https://github.com/solus-project/3rd-party/commit/d9c1a939e547b38bcebb660609383558136088ed
