### ISSUE TITLE
Some 3rd party package icons does not show up in the menu list

### ISSUE THREAD

**Issue by srcnalt** [solus-project/3rd-party#79]
After installing Spotify and GitKtaken their icons did not show up in the menu list. As for Chrome and Rubymine I did not have this problem. So I am able to start these packages from terminal or from run dialog.

Additionally, after running I can pin packages with missing icon to task list, when I run spotify from pinned icon it doubles.

![screenshot from 2016-11-20 02-52-19](https://cloud.githubusercontent.com/assets/3163281/20459505/602d997a-aecc-11e6-8d36-a82a3be72a63.png)

**Comment by JoshStrobl** [comment]
1. Sometimes they don't show up in the menu. That doesn't mean the .desktop file doesn't exist though. I've generated both Spotify and GitKraken eopkgs and they both have the resulting eopkgs.
2. This is a Budgie issue. Report to https://github.com/budgie-desktop/budgie-desktop
